### ISSUE TITLE
Beat tracker

### ISSUE THREAD

**Issue by manio143** [manio143/RiseOfTheUndeaf#2]
For the MVP the gameplay will consist of pressing a single button (any) to try to trace a beat. When button is pressed we want to check the distance from the nearest beat and if we're within a delta we mark that beat as successful.

The score will be the percentage of traced beats.

- [ ] [UI] beat timeline with beats marked and a progress bar as time moves on (bar color changes on beats)
- [ ] [UI] score indicator
- [ ] input detector and signal management
